from dataclasses import dataclass
from enum import Enum
from typing import List, Optional

from ._base import UpdatableModel, uuid_by_params
from .minified import min_models


class Status(str, Enum):
    DISPATCHED = "DISPATCHED"
    PARTIAL_DISPATCHED = "PARTIAL_DISPATCHED"


class Services(str, Enum):
    ANESTHESIOLOGY = "ANESTHESIOLOGY"
    ANGIOLOGY = "ANGIOLOGY"
    SHOCK_AREA = "SHOCK_AREA"
    CARDIOLOGY_HEMODYNAMICS = "CARDIOLOGY_HEMODYNAMICS"
    GENERAL_SURGERY = "GENERAL_SURGERY"
    PEDIATRIC_SURGERY = "PEDIATRIC_SURGERY"
    PLASTIC_RECONSTRUCTIVE_SURGERY = "PLASTIC_RECONSTRUCTIVE_SURGERY"
    VASCULAR_SURGERY = "VASCULAR_SURGERY"
    SPECIALIZED_EMERGENCY_CARE = "SPECIALIZED_EMERGENCY_CARE"
    GENERAL_SPECIALIZED_EMERGENCY_CARE = "GENERAL_SPECIALIZED_EMERGENCY_CARE"
    DERMATOLOGY = "DERMATOLOGY"
    ENDOCRINOLOGY = "ENDOCRINOLOGY"
    EPIDEMIOLOGY = "EPIDEMIOLOGY"
    GASTROENTEROLOGY = "GASTROENTEROLOGY"
    GENETICS = "GENETICS"
    OBSTETRICS_AND_GYNECOLOGY = "OBSTETRICS_AND_GYNECOLOGY"
    HEMATOLOGY = "HEMATOLOGY"
    HEMODIALYSIS = "HEMODIALYSIS"
    INFECTIOUS_DISEASES = "INFECTIOUS_DISEASES"
    INHALOTHERAPY = "INHALOTHERAPY"
    MAXILLOFACIAL_SURGERY = "MAXILLOFACIAL_SURGERY"
    INTERNAL_MEDICINE = "INTERNAL_MEDICINE"
    PREVENTIVE_MEDICINE = "PREVENTIVE_MEDICINE"
    NEPHROLOGY_HEMODIALYSIS_PERITONEAL_DIALYSIS = (
        "NEPHROLOGY_HEMODIALYSIS_PERITONEAL_DIALYSIS"
    )
    NEONATOLOGY = "NEONATOLOGY"
    PULMONOLOGY = "PULMONOLOGY"
    NEUROSURGERY = "NEUROSURGERY"
    NUTRITION_DIETETICS = "NUTRITION_DIETETICS"
    DENTISTRY = "DENTISTRY"
    OPHTHALMOLOGY = "OPHTHALMOLOGY"
    ONCOLOGY_I = "ONCOLOGY_I"
    ONCOLOGY_II = "ONCOLOGY_II"
    ENT_EAR_NOSE_THROAT = "ENT_EAR_NOSE_THROAT"
    PEDIATRICS = "PEDIATRICS"
    FAMILY_PLANNING = "FAMILY_PLANNING"
    PROCTOLOGY = "PROCTOLOGY"
    PSYCHOLOGY = "PSYCHOLOGY"
    PEDIATRIC_PSYCHIATRY = "PEDIATRIC_PSYCHIATRY"
    BURN_UNIT = "BURN_UNIT"
    PHYSICAL_REHABILITATION = "PHYSICAL_REHABILITATION"
    RHEUMATOLOGY = "RHEUMATOLOGY"
    INTENSIVE_CARE = "INTENSIVE_CARE"
    NEONATAL_INTENSIVE_CARE_UNIT = "NEONATAL_INTENSIVE_CARE_UNIT"
    INTERMEDIATE_CARE = "INTERMEDIATE_CARE"
    OBSTETRIC_SURGERY = "OBSTETRIC_SURGERY"
    TRANSPLANTS = "TRANSPLANTS"
    ADULT_EMERGENCY = "ADULT_EMERGENCY"
    OBSTETRIC_AND_GYNECOLOGY_EMERGENCY = "OBSTETRIC_AND_GYNECOLOGY_EMERGENCY"
    PEDIATRIC_EMERGENCY = "PEDIATRIC_EMERGENCY"
    UROLOGY = "UROLOGY"
    STERILIZATION_AND_PACKAGING_CENTER = "STERILIZATION_AND_PACKAGING_CENTER"
    OUTPATIENT_SURGERY = "OUTPATIENT_SURGERY"
    ENDOSCOPY_AND_SURGICAL_PROCEDURES_CENTER = (
        "ENDOSCOPY_AND_SURGICAL_PROCEDURES_CENTER"
    )
    HOSPITALIZATION = "HOSPITALIZATION"
    DIALYSIS = "DIALYSIS"
    MEDICAL_RECORDS = "MEDICAL_RECORDS"
    MILK_BANK = "MILK_BANK"
    GERIATRICS = "GERIATRICS"
    CLINICAL_PATHOLOGY = "CLINICAL_PATHOLOGY"
    BLOOD_BANK = "BLOOD_BANK"
    LABORATORY = "LABORATORY"
    ORAL_PATHOLOGY = "ORAL_PATHOLOGY"
    PALLIATIVE_CARE = "PALLIATIVE_CARE"
    PATHOLOGICAL_ANATOMY = "PATHOLOGICAL_ANATOMY"
    NUCLEAR_MEDICINE = "NUCLEAR_MEDICINE"
    IMAGING = "IMAGING"
    ALLERGY_AND_IMMUNOLOGY = "ALLERGY_AND_IMMUNOLOGY"
    AUDIOLOGY = "AUDIOLOGY"
    STOMATOLOGY = "STOMATOLOGY"
    CRITICAL_CARE = "CRITICAL_CARE"
    SURGICAL_SPECIALTIES = "SURGICAL_SPECIALTIES"
    RECONSTRUCTIVE_SURGERY = "RECONSTRUCTIVE_SURGERY"
    CARDIOVASCULAR = "CARDIOVASCULAR"
    NEUROLOGY = "NEUROLOGY"
    CARDIOVASCULAR_SURGERY = "CARDIOVASCULAR_SURGERY"
    SPECIALTIES = "SPECIALTIES"
    NEPHROLOGY = "NEPHROLOGY"
    NUTRITION = "NUTRITION"
    SURGERY = "SURGERY"
    ORTHOPEDICS = "ORTHOPEDICS"
    MIXED_PEDIATRICS = "MIXED_PEDIATRICS"
    SHORT_STAY_CHEMOTHERAPY = "SHORT_STAY_CHEMOTHERAPY"
    OUTPATIENT_CHEMOTHERAPY = "OUTPATIENT_CHEMOTHERAPY"
    RECOVERY = "RECOVERY"
    MEDICAL_THERAPY_UTIP = "MEDICAL_THERAPY_UTIP"
    SURGICAL_THERAPY = "SURGICAL_THERAPY"
    RESPIRATORY_THERAPY = "RESPIRATORY_THERAPY"
    NICU_NEONATAL_INTENSIVE_CARE_UNIT = "NICU_NEONATAL_INTENSIVE_CARE_UNIT"
    COVID = "COVID"
    RESPIRATORY_C = "RESPIRATORY_C"
    EMERGENCIES = "EMERGENCIES"
    PSYCHIATRY = "PSYCHIATRY"
    CLINDI = "CLINDI"
    CEDI = "CEDI"
    DEVELOPMENTAL_PEDIATRICS = "DEVELOPMENTAL_PEDIATRICS"
    OUTPATIENT_CONSULTATION = "OUTPATIENT_CONSULTATION"


class DispatchType(str, Enum):
    INHOSPITAL_DISPENSING = "INHOSPITAL_DISPENSING"
    PRESCRIPTION = "PRESCRIPTION"


class DispatchCategory(str, Enum):
    MEDICATION = "MEDICATION"
    MEDICAL_SUPPLIES = "MEDICAL_SUPPLIES"
    MIXED = "MIXED"


@dataclass(kw_only=True)
class DispatchRecordModel(UpdatableModel):
    __entity_name__ = "dispatch-records"

    umu_id: str
    category: str
    reference_id: str
    dispatch_type: str
    dispatch_at: int
    service: str
    status: Status
    author: min_models.UserMin
    dispatch_details: Optional[List[min_models.DispatchRecordDetailMin]] = None
    dispatch_notes: Optional[str] = None

    def __post_init__(self):
        super().__post_init__()
        self._id = uuid_by_params(self.reference_id, self.umu_id)
